-- DATABASE EXPLORATION

-- Explore all objects in the database

SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


/*=================================================================================*/
-- Dimension Exploration

SELECT DISTINCT country FROM gold.dim_customers;

SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3


-- Explore the date columns
SELECT MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales;

    -- Find the youngest and oldest customer

SELECT
MIN(birthdate) as Oldest,
MAX(birthdate) as youngest,
DATEDIFF(year, MIN(birthdate), GETDATE()) as oldest_age,
DATEDIFF(year, MAX(birthdate), GETDATE()) as youngest_age
FROM gold.dim_customers;


-- Measure Exploration
    -- Calculate the key metric of the business

-- Find the Total Sales

SELECT SUM(sales_amount) AS totla_sales
FROM gold.fact_sales;

-- Find how many items are sold

SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales;

-- Find the average selling price

SELECT AVG(price) AS avg_price
FROM gold.fact_sales;

-- Find the Total Number of Orders

SELECT COUNT(order_number) AS total_orders
FROM gold.fact_sales;
-- 60398
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;
--27659

-- Find the Total Number of products

SELECT COUNT(product_number) as total_products
FROM gold.dim_products;
--295
SELECT COUNT(product_key) as total_products
FROM gold.dim_products;
--295
SELECT COUNT(DISTINCT product_name) as total_products
FROM gold.dim_products;
--295

-- Find the Total Number of customers

SELECT COUNT(customer_number) as total_customers
FROM gold.dim_customers;
--18485
SELECT COUNT(customer_key) as total_customers
FROM gold.dim_customers;
--18485

-- Find the Total Number of customers that has placed an order

SELECT COUNT(DISTINCT customer_key) as total_customer_with_order
FROM gold.fact_sales


/*=================================================================================*/

-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Average Selling Price' as measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Orders' as measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Products' as measure_name, COUNT(DISTINCT product_name) as measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total No. Customers' as measure_name, COUNT(customer_key) as measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total No. Customer w/ Orders' as measure_name, COUNT(DISTINCT customer_key) as measure_value FROM gold.fact_sales

/*=================================================================================*/

-- Find total customers by countries

SELECT
country, 
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
group by country
order by total_customers desc


-- Find total customers by gender

SELECT
gender, 
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
group by gender
order by total_customers desc

-- Find total products by category

SELECT
category, 
COUNT(product_key) AS total_products
FROM gold.dim_products
group by category
order by total_products desc

-- What is the average cost in each category

SELECT
category, 
AVG(cost) AS avg_cost
FROM gold.dim_products
group by category
order by avg_cost desc

-- What is the total revenue generated for each category

SELECT
b.category,
SUM(a.sales_amount) AS total_revenue
FROM gold.fact_sales a
LEFT JOIN gold.dim_products b
    ON a.product_key = b.product_key
group by b.category
order by total_revenue desc


-- What is the total revenue generated by each customer

SELECT
b.customer_number,
b.first_name,
b.last_name,
SUM(a.sales_amount) AS total_revenue
FROM gold.fact_sales a
LEFT JOIN gold.dim_customers b
    ON a.customer_key = b.customer_key
group by b.customer_number, b.first_name, b.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries

SELECT
b.country,
SUM(a.quantity) AS total_sold_items
FROM gold.fact_sales a
LEFT JOIN gold.dim_customers b
    ON a.customer_key = b.customer_key
group by b.country
order by total_sold_items desc

/*=================================================================================*/
-- Ranking Analysis

-- Which 5 products generated the highest revenue

SELECT TOP 5
p.product_name,
SUM(a.sales_amount) as total_revenue
FROM gold.fact_sales a
LEFT JOIN gold.dim_products p
on a.product_key = p.product_key
group by p.product_name
order by total_revenue desc

SELECT * 
FROM (
    SELECT
    ROW_NUMBER() OVER(ORDER by SUM(a.sales_amount) DESC) as rn,
    p.product_name,
    SUM(a.sales_amount) as total_revenue
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_products p
        on a.product_key = p.product_key
    group by p.product_name
)a WHERE rn <= 5

SELECT * 
FROM (
    SELECT
    RANK() OVER(ORDER by SUM(a.sales_amount) DESC) as rn,
    p.product_name,
    SUM(a.sales_amount) as total_revenue
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_products p
    on a.product_key = p.product_key
    group by p.product_name
) a WHERE rn <= 5

-- Which 5 products generated the highest revenue

SELECT TOP 5
p.product_name,
SUM(a.sales_amount) as total_revenue
FROM gold.fact_sales a
LEFT JOIN gold.dim_products p
on a.product_key = p.product_key
group by p.product_name
order by total_revenue

SELECT * 
FROM (
    SELECT
    ROW_NUMBER() OVER(ORDER by SUM(a.sales_amount)) as rn,
    p.product_name,
    SUM(a.sales_amount) as total_revenue
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_products p
    on a.product_key = p.product_key
    group by p.product_name
) a WHERE rn <= 5

SELECT * 
FROM (
    SELECT
    RANK() OVER(ORDER by SUM(a.sales_amount)) as rn,
    p.product_name,
    SUM(a.sales_amount) as total_revenue
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_products p
    on a.product_key = p.product_key
    group by p.product_name
) a WHERE rn <= 5

-- Find the Top 10 customers who have generated the highest revenue

SELECT TOP 10
    -- ROW_NUMBER() OVER(ORDER by SUM(a.sales_amount)) as rn,
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(a.sales_amount) as total_revenue
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_customers c
    on a.customer_key = c.customer_key
    group by  
    c.customer_key,
    c.first_name,
    c.last_name
    order by total_revenue desc

-- Find the top 3 customers with the fewest orders placed

SELECT TOP 3
    -- ROW_NUMBER() OVER(ORDER by SUM(a.sales_amount)) as rn,
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT a.order_number) as total_orders
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_customers c
    on a.customer_key = c.customer_key
    group by  
    c.customer_key,
    c.first_name,
    c.last_name
    order by total_orders


